### ISSUE TITLE
LightInject doesn't register controllers

### ISSUE THREAD

**Issue by Merdok94** [seesharper/LightInject.Microsoft.AspNetCore.Hosting#1]
After adding ConfigureContainer method LightInject stopped registering controllers.

Without ConfigureContainer method all works. But I need that method

Here's the code.

public class DependencyInjectionModule : ICompositionRoot
    {
        public void Compose(IServiceRegistry container)
        {
            //register services for all api versions
            var assembly = Assembly.GetExecutingAssembly();
            container.RegisterAssembly(assembly, () => new PerContainerLifetime(), (serviceType, implementingType) => !implementingType.IsAbstract && serviceType.Namespace.StartsWith("Icons.UI") && serviceType.Namespace.EndsWith("Services"));
        }
    }

     // Use this method to add services directly to LightInject
        public void ConfigureContainer(IServiceContainer container)
        {
            container.RegisterFrom<DependencyInjectionModule>();
        }

public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvcCore();
            services.AddCors();

            services.Configure<DatabaseSettingsModel>(x =>
            {
                x.ConnectionString = Configuration.GetSection("DB_CONNECTION_STRING").Value;
            });
            services.Configure<StaticUrlSettingsModel>(Configuration.GetSection("StaticUrls"));
            services.Configure<AwsSettingsModel>(Configuration.GetSection("AWS"));
            services.Configure<EmailSettings>(x =>
            {
                x.SmtpServer = Configuration.GetSection("EmailSettings").GetSection("SmtpServer").Value;
                x.SmtpPort = int.Parse(Configuration.GetSection("EmailSettings").GetSection("SmtpPort").Value);
                x.Name = Configuration.GetSection("EmailSettings").GetSection("Name").Value;
                x.Email = Configuration.GetSection("EmailSettings").GetSection("Email").Value;
                x.Password = Configuration.GetSection("EmailSettings").GetSection("Password").Value;
            });

            services.AddMvc(options =>
            {
                options.Filters.Add(new ExceptionFilter());
                options.Filters.Add(new ValidateModelAttribute());
            })
                .AddControllersAsServices()
                .AddJsonOptions(options =>
                {
                    options.SerializerSettings.Converters.Add(new StringEnumConverter());
                    options.SerializerSettings.Converters.Add(new IsoDateTimeConverter());
                    options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                }).AddFluentValidation(configuration =>
                {
                    configuration.RegisterValidatorsFromAssemblyContaining<Startup>();
                });
         }

**Comment by seesharper** [comment]
Do you get an error message? 
Would it be possible for you to create a simple repro of this?

**Comment by Merdok94** [comment]
The app starts ok, without errors. But when I call method of controller I got error:
Unable to resolve type: App.UI.V01.Controllers.HomeController, service name:

**Comment by seesharper** [comment]
I see. Looking into it

**Comment by seesharper** [comment]
Works on my maching :) Are you sure it does not fail because of any missing dependencies?

**Comment by Merdok94** [comment]
Finally it works. The problem was that I didn't register an interface which i used on low layer of app but error was about controller and I thought I had something wrong with controller. I registered the interface and all worked. Thanks for help

**Comment by seesharper** [comment]
Great 👍

**Comment by ghost** [comment]
> Finally it works. The problem was that I didn't register an interface which i used on low layer of app but error was about controller and I thought I had something wrong with controller. I registered the interface and all worked. Thanks for help

Can you please let me know how you registered that Interface; I'm getting the same error :)
