### ISSUE TITLE
InvalidCastException from HostBuilder in ASP.NET 3.0

### ISSUE THREAD

**Issue by alexthissen** [seesharper/LightInject.Microsoft.AspNetCore.Hosting#36]
When replacing the default DI container in ASP.NET Core 3.0 (preview8-013656), using the default LightInject sample, the new HostBuilder (not WebHostBuilder) throws an InvalidCastException.

System.InvalidCastException: 'Unable to cast object of type 'Microsoft.Extensions.DependencyInjection.ServiceCollection' to type 'LightInject.IServiceContainer'.'

Stacktrace:    at Microsoft.Extensions.Hosting.Internal.ConfigureContainerAdapter`1.ConfigureContainer(HostBuilderContext hostContext, Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at ASPNETCore30WebApp.Program.Main(String[] args) in C:\Sources\GitHub\alexthissen\LightInjectBugRepro\ASPNETCore30WebApp\Program.cs:line 18

Repro at https://github.com/alexthissen/LightInjectBugRepro

**Comment by seesharper** [comment]
Closed by https://github.com/alexthissen/LightInjectBugRepro/commit/3dab9aba5668f47a5a73d3f1836f1912ecd523da
