### ISSUE TITLE
Support for HostBuilder?

### ISSUE THREAD

**Issue by Mike-EEE** [seesharper/LightInject.Microsoft.AspNetCore.Hosting#50]
Happy New Years. 🎉😁

I have been checking this out and integrating it... but in my case I am not using ASP.NET Core but the (new?) `Microsoft.Extensions.Hosting.IHostBuilder`.  Is it possible to use this rather than having a dependency on AspNetCore?

Thank you for any consideration. 👍

**Comment by Mike-EEE** [comment]
FWIW, this was as simple as making use of the `UseServiceProviderFactory` [method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostbuilder.useserviceproviderfactory?view=dotnet-plat-ext-3.1):

https://github.com/DragonSpark/Framework/blob/40bcbb317323b9b8062812f70de095eaa69b9ec1/DragonSpark.Composition/ExtensionMethods.Container.cs#L11-L22

**Comment by seesharper** [comment]
Hi Mike and happy new years to you too. 
Sorry for the late reply, but I'm currently recovering from a bad case of Man flu. 😂 Against all odds it now looks like I'll survive 👍

Anyways, back to business. 

We actually have a package for this now. 

https://www.nuget.org/packages/LightInject.Microsoft.Hosting/

This package can be used independently of AspNet Core and only relies on the Generic Host (IHostBuilder)

**Comment by Mike-EEE** [comment]
LOL... Man flu!  Very nice work there... both in your recovery and the deployed package! 😁  Now I can delete some code. 👍
