### ISSUE TITLE
Application Insights incompatability

### ISSUE THREAD

**Issue by Frederik91** [seesharper/LightInject.Microsoft.AspNetCore.Hosting#56]
When combining[ Application Insights](https://www.nuget.org/packages/Microsoft.ApplicationInsights/) and LightInject an exceptrions in thrown with this message: 

> InvalidOperationException: Unresolved dependency [Target Type: Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.AzureAppServiceRoleNameFromHostNameHeaderInitializer], [Parameter: webAppSuffix(System.String)], [Requested dependency: ServiceType:System.String, ServiceName:]

> 

When removing either of them the application will start.

I have created a very simple [example ](https://github.com/Frederik91/LightInjectApplicationInsightIssueReprod)to demontstrate this issue.

I am not sure if this is something that can/has to be fixed in LightInject or if it's an issue with Application Insights. Do you have any idea what might cause this issue?

**Comment by seesharper** [comment]
This is indeed something in LightInject. I'll have a look. Thanks for the repro 👍

**Comment by seesharper** [comment]
I see what's going on here 

```
public AzureAppServiceRoleNameFromHostNameHeaderInitializer(string webAppSuffix = ".azurewebsites.net")
```

It is a string dependency with a default value. `LightInject` does not take that into consideration. I'll look into it

**Comment by Frederik91** [comment]
Good catch! I can confirm that this is the case. 

When adding 
`container.RegisterInstance(".azurewebsites.net");`
to ConfigureContainer method it manages to resolve this dependency and the application starts.

**Comment by seesharper** [comment]
LightInject now supports optional arguments. Update to 1.2.0 should fix the problem 👍

`<PackageReference Include="LightInject.Microsoft.Hosting" Version="1.2.0" />`

**Comment by Frederik91** [comment]
I have tested version 1.2.0 and can confirm that it solved the issue, thanks! 🥇
